### ISSUE TITLE
Can't run onedrived-pref

### ISSUE THREAD

**Issue by daviddavo** [derrix060/onedriveClient#2]
I'm using a raspbian. xybu/onedrived-dev was working perfectly
```
pi@bpi-iot-ros-ai:~/Bak $ onedrived-pref 
Traceback (most recent call last):
  File "/usr/local/bin/onedrived-pref", line 11, in <module>
    load_entry_point('onedrived==2.0.0', 'console_scripts', 'onedrived-pref')()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/pi/.local/lib/python3.4/site-packages/onedrived/od_pref.py", line 13, in <module>
    from . import mkdir, get_resource, od_auth, od_i18n
  File "/home/pi/.local/lib/python3.4/site-packages/onedrived/od_auth.py", line 18, in <module>
    from . import od_api_session, od_i18n, od_pref
ImportError: cannot import name 'od_pref'
pi@bpi-iot-ros-ai:~/Bak $ python
python             python2.7          python3.4          python3.4m         python3-config     python3m-config    
python2            python3            python3.4-config   python3.4m-config  python3m           
pi@bpi-iot-ros-ai:~/Bak $ python --version
Python 2.7.9
pi@bpi-iot-ros-ai:~/Bak $ python3 --version
Python 3.4.2
```

**Comment by derrix060** [comment]
Thank you!! Try to run this code:
`python3 -m onedrived.od_pref `

**Comment by daviddavo** [comment]
Almost the same
```
pi@bpi-iot-ros-ai:~ $ python3 -m onedrived.od_pref
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/.local/lib/python3.4/site-packages/onedrived/od_pref.py", line 13, in <module>
    from . import mkdir, get_resource, od_auth, od_i18n
  File "/home/pi/.local/lib/python3.4/site-packages/onedrived/od_auth.py", line 18, in <module>
    from . import od_api_session, od_i18n, od_pref
  File "/home/pi/.local/lib/python3.4/site-packages/onedrived/od_pref.py", line 13, in <module>
    from . import mkdir, get_resource, od_auth, od_i18n
ImportError: cannot import name 'od_auth'
```

**Comment by derrix060** [comment]
That's embarrassing... Have you used this commands?

`
$ git clone https://github.com/derrix060/onedriveClient.git
`
`
$ cd onedrived-dev
`
`
$ pip3 install -e .
`

And have uninstalled the old onedrive ??

**Comment by dipusone** [comment]
I can reproduce the issue. Event trying to install it in a virtualenv gives the same result. If you need i can "produce" logs :).

**Comment by derrix060** [comment]
Hello @dipusone this would be good.

**Comment by dipusone** [comment]
Let me know if you need specific tests, meanwhile i will try to figure out why is not able to import the module.

**Comment by dipusone** [comment]
I've solved the problem. There where some circular imports which would not resolve. As soon i've managed to test the installation i will make a PR.

**Comment by dipusone** [comment]
@derrix060 I've refactored the classes and the methods in order to adhere to the main application structure and removed the cyclic imports which caused the problems. I've made a PR #5 with the changes.

**Comment by derrix060** [comment]
@dipusone Thank you for your contribution. 

@daviddavo, could you check if the problem persist?

**Comment by daviddavo** [comment]
1. Uninstalled old packages
2. Removed config
3. Updated pip
4. Followed the "to run on raspberry pi you'll need..."
5. Can't find dbus-devel, but dbus is installed alredy
6. Followed pre-requisites
7. Installed arm ngrok
8. `sudo pip3 install git+https://github.com/derrix060/onedriveClient.git`

Running either `onedrived` or `onedrived-pred` gives the same error:
```
Traceback (most recent call last):
  File "/usr/local/bin/onedrived-pref", line 11, in <module>
    load_entry_point('onedrived==2.0.0', 'console_scripts', 'onedrived-pref')()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/pi/.local/lib/python3.4/site-packages/onedrived/od_pref.py", line 13, in <module>
    from . import mkdir, get_resource, od_auth, od_i18n
  File "/home/pi/.local/lib/python3.4/site-packages/onedrived/od_auth.py", line 18, in <module>
    from . import od_api_session, od_i18n, od_pref
ImportError: cannot import name 'od_pref'
```
¿Maybe is related to the dbus-devel package?

**Comment by dipusone** [comment]
mmm, are you sure the uninstaller didn't left any package behind? After my edit od_auth.py does not impor anymore od_pref.py. 
May be try an hard remove by:
pip uninstall onedrived
rm -rf /home/pi/.local/lib/python3.4/site-packages/onedrived

This should remove any leftover files.

**Comment by daviddavo** [comment]
Ok, I've been able to set up my account and a drive, but when I try to start the daemon...
```
$ sudo onedrived start
Starting onedrived ... FAILED
ERROR: Child exited immediately with exit code 127
```

**Comment by daviddavo** [comment]
Okay... This is pretty strange. When I started with `--debug` it worked fine, it asked me for my keyring and now is syncing and working, thanks

**Comment by derrix060** [comment]
@daviddavo is it working now?

@dipusone is it working to you?

**Comment by daviddavo** [comment]
If I do `onedrived start` it returns:
```
Starting onedrived ... FAILED
ERROR: Child exited immediately with exit code 127
```
But if I do `--debug` it works fine. I think it has problems with the `detaching`
