### ISSUE TITLE
Syncing from web to local onOneDrive for Business

### ISSUE THREAD

**Issue by Modelmat** [derrix060/onedriveClient#21]
Deleting/creating an item from the web client results in the error below, failing the delete/create The value for KeyError varies within 1000-7000 (from what I've seen). Fine deleting / creating files on local and uploading. The initial sync worked, just later updates do not. This makes this program useless.

*also should I be worried when --debug shows a large amount of adding watcher for {file}*?
```
source_traceback: Object created at (most recent call last):
  File "/home/modelmat/.local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/modelmat/.local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/modelmat/.local/lib/python3.7/site-packages/daemonocle/cli.py", line 57, in subcommand
    daemon.do_action(name)
  File "/home/modelmat/.local/lib/python3.7/site-packages/daemonocle/core.py", line 608, in do_action
    func()
  File "/home/modelmat/.local/lib/python3.7/site-packages/daemonocle/core.py", line 477, in start
    self._run()
  File "/home/modelmat/.local/lib/python3.7/site-packages/daemonocle/core.py", line 399, in _run
    self.worker()
  File "/home/modelmat/.local/lib/python3.7/site-packages/onedrived/od_main.py", line 204, in main
    context.watcher = LocalRepositoryWatcher(task_pool=task_pool, loop=context.loop)
  File "/home/modelmat/.local/lib/python3.7/site-packages/onedrived/od_watcher.py", line 46, in __init__
    self.loop.add_reader(self.notifier.fd, self.process_events)
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 335, in add_reader
    return self._add_reader(fd, callback, *args)
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 260, in _add_reader
    handle = events.Handle(callback, args, self, None)
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/modelmat/.local/lib/python3.7/site-packages/onedrived/od_watcher.py", line 441, in process_events
    self.handle_event(ev, flags, move_pairs)
  File "/home/modelmat/.local/lib/python3.7/site-packages/onedrived/od_watcher.py", line 339, in handle_event
    repo, parent_dir = self.watch_descriptors[ev.wd]
  File "/home/modelmat/.local/lib/python3.7/site-packages/bidict/_common.py", line 96, in proxy
    return meth(*args)
KeyError: 1811
```

**Comment by derrix060** [comment]
That's weird because I use it every day and is working fine here... I'm wondering if can be something related with python3.7...

Anyway, I will look a this.


The number of " adding watcher for {file}" will depend on your configuration. You can see it on the `onedrived_config_v2.json`.

**Comment by Modelmat** [comment]
So that's normal when in debug? Great!
Thanks for having a look. If you need anything tested, I know my way around python so it should be fine.

**Comment by derrix060** [comment]
I could reproduce it here. What I've found is the program logs this error, but the file/directory is created/deleted....

**Comment by Modelmat** [comment]
So it works but it errors?

**Comment by Modelmat** [comment]
Oh, okay.

**Comment by Modelmat** [comment]
I've had a look at this again and it seems that this only occurs when I create a file with one name then (very) quickly rename it, then it spams the KeyError continuously. If it's not so quick it only does the KeyError once.

**Comment by Modelmat** [comment]
I've had a look at this again and it seems that this only occurs when I create a file with one name then (very) quickly rename it, then it spams the KeyError continuously. If it's not so quick it only does the KeyError once.

**Comment by derrix060** [comment]
So even with the KeyError the sync could be completed?
