### ISSUE TITLE
Can't find onedrive_config.yml

### ISSUE THREAD

**Issue by Daryolo** [derrix060/onedriveClient#7]
I'm getting an error when I try to add a Account.

onedrived-pref account add -b

Traceback (most recent call last):
  File "/usr/local/bin/onedrived-pref", line 11, in <module>
    load_entry_point('onedrived==2.0.0', 'console_scripts', 'onedrived-pref')()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2409, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2415, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/onedrived-2.0.0-py3.5.egg/onedrived/od_pref.py", line 13, in <module>
    from . import mkdir, get_resource, od_i18n, od_auth
  File "/usr/local/lib/python3.5/dist-packages/onedrived-2.0.0-py3.5.egg/onedrived/od_auth.py", line 26, in <module>
    with open(os.path.abspath(path + '/onedrive_config.yml'), 'r', encoding='utf8') as yml:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.5/dist-packages/onedrived-2.0.0-py3.5.egg/onedrive_config.yml'

**Comment by Daryolo** [comment]
Okay I fixed this error by moving the file with "sudo cp /home/pi/onedriveClient/onedrive_config.yml /usr/local/lib/python3.5/dist-packages/onedrived-2.0.0-py3.5.egg/"

Any idea why this isn't in the correct location after the installation?

**Comment by rodom** [comment]
Getting something very similar myself:
```rodom@oe2134:~$ onedrived-pref account add --for-business
Traceback (most recent call last):
  File "/usr/local/bin/onedrived-pref", line 11, in <module>
    load_entry_point('onedrived==2.0.0', 'console_scripts', 'onedrived-pref')()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2752, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/onedrived/od_pref.py", line 13, in <module>
    from . import mkdir, get_resource, od_i18n, od_auth
  File "/usr/local/lib/python3.5/dist-packages/onedrived/od_auth.py", line 26, in <module>
    with open(os.path.abspath(path + '/onedrive_config.yml'), 'r', encoding='utf8') as yml:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.5/dist-packages/onedrive_config.yml'
```
Similar errors whatever onedrived or onedrived-pref command I run. I grabbed it from the repo and put it there, but then I get another error:
```rodom@oe2134:~$ onedrived-pref account add --for-business
Traceback (most recent call last):
  File "/usr/local/bin/onedrived-pref", line 11, in <module>
    load_entry_point('onedrived==2.0.0', 'console_scripts', 'onedrived-pref')()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2752, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/onedrived/od_pref.py", line 13, in <module>
    from . import mkdir, get_resource, od_i18n, od_auth
  File "/usr/local/lib/python3.5/dist-packages/onedrived/od_auth.py", line 27, in <module>
    acc_config = yaml.load(yml)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 128, in peek_token
    self.fetch_more_tokens()
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 220, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 576, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "/usr/local/lib/python3.5/dist-packages/onedrive_config.yml", line 316, column 24
```
At this point I'm out of ideas. Anyone have any pointers?

**Comment by derrix060** [comment]
I'm so sorry for the delay, I've been very busy since I've moved to New Zealand. I fixed it in the last commits, can you check to see if it's happening again?
